services:
  postgres:
    image: postgres:15.6-alpine3.19
    restart: unless-stopped
    environment:
      - POSTGRES_DB=airflow
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=password
    volumes:
      - dev_pg_volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  sftp-server:
    image: emberstack/sftp:build-5.1.70
    ports:
      - "22:22"
    volumes:
      - ./dev-configs/sftp-configs.json:/app/config/sftp.json
      - ./data/sftp:/home/dev/sftp

volumes:
  dev_pg_volume:
