services:
  airflow-db:
    image: postgres:15.6-alpine3.19
    environment:
      - POSTGRES_DB=${AIRFLOW_DB}
      - POSTGRES_USER=${AIRFLOW_DB_USER}
      - POSTGRES_PASSWORD=${AIRFLOW_DB_PASSWORD}
    volumes:
      - dev_pg_volume:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5433:5432
    deploy:
      resources:
        reservations:
          cpus: "0.5"
          memory: 100M
        limits:
          cpus: "1"
          memory: 200M

  airflow:
    image: ghcr.io/meteorflow/mf-airflow:latest
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASSWORD}@airflow-db/${AIRFLOW_DB}
      - AIRFLOW__CORE__FERNET_KEY=${AIRFLOW_DB_FERNET_KEY}

volumes:
  dev_pg_volume:

networks:
  meteorflow-network:
    name: meteorflow-network
