name: prod-airflow

services:
  airflow-db:
    image: postgres:15.6-alpine3.19
    environment:
      - POSTGRES_DB=${AIRFLOW_DB}
      - POSTGRES_USER=${AIRFLOW_DB_USER}
      - POSTGRES_PASSWORD=${AIRFLOW_DB_PASSWORD}
    volumes:
      - pg_volume:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    deploy:
      resources:
        reservations:
          cpus: "0.5"
          memory: 100M
        limits:
          cpus: "1"
          memory: 200M

volumes:
  pg_volume:

networks:
  meteorflow-network:
    name: meteorflow-network
